[package]
name = "aoc2024"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.23", features = ["derive"] }
count-digits = "0.5.1"
itertools = "0.13.0"
lazy_static = "1.5.0"
num = "0.4.3"
progress_bar = "1.0.6"
regex = "1.11.1"
substring = "1.4.5"
