[package]
name = "aoc2024"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.23", features = ["derive"] }
itertools = "0.13.0"
lazy_static = "1.5.0"
progress_bar = "1.0.6"
regex = "1.11.1"
